/**
 * The 550C variant — the original machine, and the only one with a shipped
 * timeline.
 *
 * This file is the whole of "what makes 550C 550C" as far as the client half is
 * concerned: a background colour, a stylesheet, two markup strings and the two
 * functions that drive them. Everything it references is ported verbatim —
 * `assets.js`/`show.js` are generated by scripts/extract.mjs from
 * assets/550C-source.html, and `enhance.js` is the hand-written layer that
 * upgrades the ported content (terminal type, self-consistent clock stamps,
 * CRC32 footer) without touching it. Nothing in here is 550C-specific in a way
 * the registry could not ask another machine for.
 *
 * Shape (see src/variants/registry.js for the contract):
 *   boot, app     markup per stage; `app` is null for a machine with no
 *                 full-mode surface (full mode then plays `boot` only)
 *   css           the machine's stylesheet, including its own default palette
 *   show          createShow(stage, { mode, cancelled })
 *   enhance       enhanceShow(stage, { mode }) -> disposer
 *   watchdogMs    safety net per mode; must outlive the machine's own timeline
 *
 * The machine's background colour is NOT here: it lives in the registry's
 * VARIANT_BG table, because the host half has to reach the same value before any
 * of this code runs.
 */
const VARIANT_550C = {
  id: '550c',
  label: '550C',
  boot: BOOT_MARKUP,
  app: APP_MARKUP,
  css: CSS_550C,
  show: createShow,
  enhance: enhanceShow,
  watchdogMs: { simple: 12000, full: 30000 },
}
