/**
 * The hole in the shared boot template — and the only place it is filled.
 *
 * 550W's opening is the same STARTUP APPARATUS as 550C's and on the same clock:
 * the same `#boot` stage, the same scanning overlay, the same per-path
 * `clip-path` write-on sorted by `getBBox().x` on the `250 + i*300` beat, the
 * same `#logo.finished` glow, the same `#bootText` beat at 2400 ms, the same
 * skip paths. What is NOT 550C's any more is the wordmark inside `<g id="logo">`
 * — see the next paragraph, that is a deliberate trade with a cost.
 *
 * WHY THE WORDMARK IS A HOLE AND NOT A TAIL GLYPH. The master still's ink never
 * crosses between white and red: the smallest red↔white gap is 48 px (9.0 % of
 * the 533 px cap height) and there are zero orthogonally adjacent red/white
 * pixel pairs. Its third glyph is an OPEN ARC inside which the red W sits, and
 * its strokes run across glyph boundaries. 550C's third glyph is a CLOSED oval,
 * so no placement of a traced tail can avoid crossing white ink — measured: the
 * best interleaved placement still leaves 1 px of red↔white contact and 133
 * touching pixel pairs. The mark had to be replaced as a whole, from the master.
 *
 * COST, stated plainly (skill §0): a0 is no longer "550C's own markup with two
 * values swapped". It is "550C's startup apparatus and cadence, with the master's
 * wordmark". The assertion below still proves a byte-exact relationship — it
 * just proves a smaller object than it used to: that the template, filled with
 * 550C's own logo contents, still reproduces 550C's ported BOOT_MARKUP byte for
 * byte, so the apparatus around the wordmark cannot drift.
 *
 * Only finished markup is ever emitted: the client bundle is loaded as a
 * `<script>`, `scripts/build.mjs` refuses any output containing `<!--`, and the
 * hole IS an HTML comment. The template keeps it; the generator never emits it.
 */

export const WORDMARK_HOLE = '<!--550W-WORDMARK-->'

/**
 * 550C's own `playBoot()`, parameterised: the body is copied verbatim from the
 * ported original, and the two dependencies the page's closure used to supply
 * for free are passed in (the stage to query, and the caller's cancellable
 * `later()`). `assertSharedTimelineMatches550C()` re-reads the fragments below
 * out of 550C's ported script on every extract, so "same apparatus, same
 * cadence" stays a build-time fact rather than a comment.
 */
const PLAY_BOOT_SHARED = `function playBootShared(deps) {
  const stage = deps.stage;
  const later = deps.later;
  const logo = stage.querySelector('#logo');
  const bootText = stage.querySelector('#bootText');
  const paths = Array.from(logo.querySelectorAll('path'));

  paths.forEach(p => {
    p.style.opacity = '0.08';
    p.style.clipPath = 'inset(0 0 0 0)';
    p.style.webkitClipPath = 'inset(0 0 0 0)';
  });

  const sorted = paths.map(p => ({el: p, x: p.getBBox().x})).sort((a, b) => a.x - b.x);

  sorted.forEach((item, i) => {
    const delay = 250 + i * 300;
    later(() => {
      const p = item.el;
      p.style.clipPath = 'inset(0 100% 0 0)';
      p.style.webkitClipPath = 'inset(0 100% 0 0)';
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          p.style.transition = 'clip-path .6s cubic-bezier(.4,0,.2,1), opacity .35s ease';
          p.style.opacity = '1';
          p.style.clipPath = 'inset(0 0 0 0)';
          p.style.webkitClipPath = 'inset(0 0 0 0)';
        });
      });
    }, delay);
  });

  later(() => bootText.classList.add('show'), 2400);
  const totalMs = 250 + sorted.length * 300 + 400;
  later(() => logo.classList.add('finished'), totalMs);
  return totalMs + 600;
}`

/** The beats the shared timeline has to keep, byte for byte, from 550C's own. */
const TIMING_FRAGMENTS = [
  "p.style.opacity = '0.08';",
  'const sorted = paths.map(p => ({el: p, x: p.getBBox().x})).sort((a, b) => a.x - b.x);',
  'const delay = 250 + i * 300;',
  "p.style.clipPath = 'inset(0 100% 0 0)';",
  "later(() => bootText.classList.add('show'), 2400);",
  'const totalMs = 250 + sorted.length * 300 + 400;',
  'return totalMs + 600;',
]

/** The shared opening, as the module scripts/extract.mjs emits. */
export function sharedBootSource(bootMarkup550W) {
  return (
    `/* shared/boot — the opening apparatus 550C and 550W share, plus 550W's own\n` +
    ` * master-traced wordmark. Generated by scripts/extract.mjs: the template's\n` +
    ` * <g id="logo"> hole is filled HERE, at build time, so the emitted markup is\n` +
    ` * finished — the bundle is loaded as a <script> and cannot contain the hole's\n` +
    ` * HTML comment. playBootShared() is 550C's own playBoot(), parameterised; see\n` +
    ` * scripts/boot-shared.mjs for the fragments that keep the cadence identical. */\n` +
    `const BOOT_MARKUP_550W = ${JSON.stringify(bootMarkup550W)};\n\n` +
    PLAY_BOOT_SHARED +
    '\n'
  )
}

/**
 * Every beat of the shared timeline must still be 550C's own expression. Pass
 * 550C's ported `playBoot()` body; both sides are checked, so this fails if
 * either the port or the shared copy drifts.
 */
export function assertSharedTimelineMatches550C(portBody550C) {
  for (const fragment of TIMING_FRAGMENTS) {
    if (!portBody550C.includes(fragment)) {
      throw new Error(`boot-shared: 550C's playBoot() no longer contains ${JSON.stringify(fragment)}`)
    }
    if (!PLAY_BOOT_SHARED.includes(fragment)) {
      throw new Error(`boot-shared: the shared playBootShared() no longer contains ${JSON.stringify(fragment)}`)
    }
  }
}

const LOGO_OPEN = '<g id="logo" filter="url(#despike)">'

/**
 * The contents of the boot markup's `<g id="logo">` — everything between the
 * open tag and its matching close tag, byte for byte.
 */
export function logoContentOf(bootMarkup) {
  const open = bootMarkup.indexOf(LOGO_OPEN)
  if (open === -1) throw new Error(`boot-shared: no ${LOGO_OPEN} in the 550C boot markup`)
  const start = open + LOGO_OPEN.length
  const tag = /<g\b|<\/g>/g
  tag.lastIndex = start
  // The logo group itself is already open: its own closing tag is the one that
  // takes the depth back to 0.
  let depth = 1
  let match
  while ((match = tag.exec(bootMarkup)) !== null) {
    depth += match[0] === '</g>' ? -1 : 1
    if (depth === 0) return bootMarkup.slice(start, match.index)
  }
  throw new Error('boot-shared: unbalanced <g id="logo"> in the 550C boot markup')
}

/** The `<g>` body of a traced wordmark file (drops the leading comment). */
export function wordmarkBodyOf(art) {
  return art.replace(/^<!--[\s\S]*?-->\s*/, '').trim()
}

/** Fill the wordmark hole with a finished `<g id="logo">` body. */
export function fillBootTemplate(template, wordmark) {
  if (!template.includes(WORDMARK_HOLE)) {
    throw new Error(`boot-shared: assets/boot-template.html is missing ${WORDMARK_HOLE}`)
  }
  const body = wordmark.trim()
  if (body.includes(WORDMARK_HOLE)) throw new Error('boot-shared: the wordmark still contains the template hole')
  if (!body.includes('<g ')) throw new Error('boot-shared: the wordmark has no groups in it')
  return template.replace(WORDMARK_HOLE, body)
}

/**
 * The load-bearing assertion: 550C's own logo contents in the hole must
 * reproduce 550C's ported `BOOT_MARKUP` byte for byte. One byte edited in
 * assets/boot-template.html makes `npm run extract` exit 1 with this message.
 */
export function assertTemplateMatches550C(template, bootMarkup550C) {
  const filled = fillBootTemplate(template, logoContentOf(bootMarkup550C))
  if (filled !== bootMarkup550C) {
    throw new Error(
      "boot-shared: assets/boot-template.html no longer matches 550C's ported #boot markup — " +
        "fill the wordmark hole with 550C's own <g id=\"logo\"> contents and it must be byte-identical " +
        `(template ${template.length} chars, ported ${bootMarkup550C.length} chars, filled ${filled.length})`,
    )
  }
  return filled
}
