/* 550W — 月面接管：stylesheet + app markup.
 *
 * Hand-written on purpose. 550C's assets.js is a mechanical port of somebody
 * else's page and is regenerated by scripts/extract.mjs; 550W is our own
 * machine, so its sheet is authored here. The ONE thing it does not author is
 * the boot stage: that markup comes from the shared template
 * (assets/boot-template.html -> src/variants/shared/boot.js) so the opening
 * cannot drift from 550C's, and the tail glyph is traced out of the reference
 * still by tools/trace-550w-mark.mjs into assets/550w-tail-glyph.svg.
 *
 * Palette: greys plus the selected accent in the workbench. The user's two
 * explicit exceptions are isolated: 550C amber in the final banner and a pale
 * blue plume in the Earth/engine drawings. Phosphor settings still swap the
 * workbench accent without recolouring either exception.
 *
 * Reuse is deliberate: `.w` corner panels, `.w-head`, `.dt/.k/.v/.sect`, `.ln`
 * log lines, the `.win-popup` family and the two HUD bars are 550C's components
 * with 550W's tokens. The content is the Lunar Fall Crisis: three Lunar Engine
 * sites, the 3,751-warhead phased array in Campanus Crater, the Space Station as
 * relay, and the countdown to detonation.
 *
 * One square decides the map: `.moon` is the master situation display's frame,
 * and the disc, the three sites, Campanus, the warhead field and the Earth all
 * live inside it in percent-of-box coordinates. That is what keeps the diagram
 * coherent at any viewport — nothing on the map is positioned against the
 * viewport while its neighbours are positioned against the disc.
 *
 * Optical polish: 550C's head gradients, title glows, panel inset and popup
 * shadows in neutral greys. Instrument grids, ticks, bases and range ruler are
 * STATIC geometry, not the old flying/scanning lines. Only the <=8px LED is
 * exempt from the 2.5s opacity-loop rule. Beat timing and popup dwells stay R4.
 */

/**
 * The four grey levels are the skill's measured tokens, unchanged. `--acc`
 * remains the workbench accent; `--amber` is final-only and `--plume` is
 * Earth-ignition-only. Ordinary labels/progress do not inherit those exceptions.
 *
 * The WORDMARK carries its own pair on top of those: `--mark-ink` / `--mark-red`
 * are the master still's measured ink (white 253,253,253 ≈ `#fff`; red
 * 229,19,24 = `#e7141b`), and `--mark-ink-glow` / `--mark-red-glow` are their
 * alpha companions so the glow cannot drift away from the fill. `amber` is the
 * "override nothing" row and therefore IS the master pair; the three phosphor
 * rows override all four together (asserted by tools/measure-550w-wordmark.mjs
 * and by the four scheme stills). `--acc` keeps its narrow meaning — warnings,
 * countdown, ignition, selection and 550W identity — and the wordmark must
 * NOT: the film's mark is a brand colour, not the interface accent.
 */
const CSS_550W = `
  :host{
    --bg:#030303; --panel:#0a0a0a; --win:#0a0a0a;
    --ink:#e8e8e8; --dim:#909090; --faint:#4c4c4c; --ghost:#262626;
    --acc:#d8352a; --acc-b:#ff5a48; --acc-glow:216,53,42;
    --amber:#e8a020; --amber-b:#ffc043;
    --plume:#9fd0ff; --plume-glow:159,208,255;
    --mark-ink:#fff; --mark-red:#e7141b;
    --mark-ink-glow:rgba(255,255,255,.45);
    --mark-red-glow:rgba(231,20,27,.55);
    --crt:0;
    --grid:.8vmin;--pad:1.1vmin;--row:1.6vmin;
    --fs-note:.85vmin;--fs-head:.88vmin;--fs-key:.95vmin;--fs-data:1.1vmin;--fs-body:1.2vmin;
    --fs-big:clamp(30px,4.4vw,58px);--fs-sub:calc(var(--fs-big) / 2);
    --font-cjk:"SF Mono",Menlo,Monaco,Consolas,"Courier New",monospace;
    --font-latin:"SF Mono",Menlo,Monaco,Consolas,"Courier New",monospace;
    --font-mono:"SF Mono",Menlo,Monaco,Consolas,"Courier New",monospace;
    --caption-fill:#030303; --caption-symbol:#909090;
  }
  /* [FAN] phosphor variants: swap the accent, keep the structure. Never a second
     hue beside the accent — the accent IS what changes. The wordmark's four mark
     tokens are overridden in the same block, so the fill and its glow always move
     together. */
  :host([data-scheme="green"]){--acc:#3fae62;--acc-b:#79e29b;--acc-glow:63,174,98;--crt:.45;--caption-symbol:#79e29b;
    --mark-ink:#eaf7ee;--mark-red:var(--acc);
    --mark-ink-glow:rgba(234,247,238,.45);--mark-red-glow:rgba(63,174,98,.55)}
  :host([data-scheme="cyan"]){--acc:#3f9fb8;--acc-b:#83d9ea;--acc-glow:63,159,184;--crt:.45;--caption-symbol:#83d9ea;
    --mark-ink:#e8f6fa;--mark-red:var(--acc);
    --mark-ink-glow:rgba(232,246,250,.45);--mark-red-glow:rgba(63,159,184,.55)}
  :host([data-scheme="white"]){--acc:#9c9c9c;--acc-b:#efefef;--acc-glow:156,156,156;--crt:.45;--caption-symbol:#efefef;
    --mark-ink:#f4f4f4;--mark-red:var(--acc);
    --mark-ink-glow:rgba(244,244,244,.45);--mark-red-glow:rgba(156,156,156,.55)}

  *{box-sizing:border-box;margin:0;padding:0}
  :host{height:100%;background:var(--bg);color:var(--ink);font-family:var(--font-mono);
    font-size:12px;line-height:1.55;overflow:hidden;-webkit-font-smoothing:antialiased}
  /* Frozen host CRT treatment; the app also owns its always-on vignette. */
  :host::before{content:"";position:fixed;inset:0;pointer-events:none;z-index:900;opacity:var(--crt);
    background:repeating-linear-gradient(to bottom,rgba(0,0,0,0) 0,rgba(0,0,0,0) 2px,rgba(0,0,0,.42) 2px,rgba(0,0,0,.42) 3px)}
  :host::after{content:"";position:fixed;inset:0;pointer-events:none;z-index:899;opacity:var(--crt);
    background:radial-gradient(ellipse at center,transparent 46%,rgba(0,0,0,.88) 100%)}

  /* ===== 开机动画（与 550C 同一套实体：这里的规则只负责给共享 markup 上色） ===== */
  #boot{position:fixed;inset:0;z-index:2000;background:#000;transition:opacity .55s ease}
  #boot.fade{opacity:0;pointer-events:none}
  .boot-stage{position:relative;width:100%;height:100%;display:flex;align-items:center;justify-content:center}
  .boot-stage svg{width:min(680px,90vw);height:auto;overflow:visible}
  .white{fill:var(--mark-ink);stroke:none}
  .red{fill:var(--mark-red);stroke:none}
  #logo.finished .white{animation:glowW 2.6s ease-in-out infinite}
  #logo.finished .red{animation:glowR 2.6s ease-in-out infinite}
  @keyframes glowW{0%,100%{filter:drop-shadow(0 0 6px var(--mark-ink-glow))}50%{filter:drop-shadow(0 0 14px var(--mark-ink-glow))}}
  @keyframes glowR{0%,100%{filter:drop-shadow(0 0 8px var(--mark-red-glow))}50%{filter:drop-shadow(0 0 18px var(--mark-red-glow))}}
  .boot-text{position:absolute;left:0;right:0;bottom:12%;text-align:center;color:var(--dim);
    font-family:"Courier New",Consolas,monospace;font-size:12px;letter-spacing:.4em;padding-left:.4em;opacity:0}
  .boot-text.show{animation:fadeIn .6s ease forwards}
  .boot-text .cursor{display:inline-block;width:6px;height:12px;background:var(--ink);margin-left:8px;
    vertical-align:-2px;animation:blink 1s steps(1) infinite}
  @keyframes blink{0%,49%{opacity:1}50%,100%{opacity:0}}
  @keyframes fadeIn{to{opacity:1}}

  /* ===== 主界面骨架（同 550C：顶栏 / 主显示 / 底栏） ===== */
  #app{height:100%;display:grid;grid-template-rows:calc(var(--grid)*4) 1fr calc(var(--grid)*4);
    padding:var(--grid);gap:var(--grid);opacity:0;font-size:var(--fs-data);font-variant-numeric:tabular-nums}
  #app.visible{opacity:1}
  /* Four independent reveals start UNDER the frozen boot cover. Geometry is
     static; only visibility changes, with 180 ms spacing over a 2.44 s span. */
  #hud-top,#hud-bot,.work-panel,.ly-map,.labs{opacity:0;transition:opacity 1.2s linear}
  #app.visible #hud-top,#app.visible #hud-bot,#app.visible #w-engine{opacity:1}
  #app.visible #w-engine{transition-duration:1.6s}
  #app.visible #w-term{opacity:1;transition-delay:.18s;transition-duration:1.8s}
  #app.visible #w-bus{opacity:1;transition-delay:.36s;transition-duration:2s}
  #app.visible .ly-map,#app.visible .labs{opacity:1;transition-delay:.54s;transition-duration:2.2s}
  /* Narrow workstations carry denser panels per screen pixel. Staggered, slower
     reveals preserve the same beats without spending the entire opening budget. */
  @media (max-aspect-ratio: 8/5){
    #hud-top,#hud-bot{transition-duration:1.8s}
    #app.visible #w-engine{transition-duration:2.1s}
    #app.visible #w-term{transition-duration:2.3s}
    #app.visible #w-bus{transition-duration:2.8s}
    #app.visible .ly-map,#app.visible .labs{transition-duration:2.7s}
  }
  #app::after{content:"";position:fixed;inset:0;pointer-events:none;z-index:899;
    background:radial-gradient(ellipse at center,transparent 45%,rgba(0,0,0,.88) 100%)}
  #hud-top{display:flex;align-items:center;gap:var(--grid);padding:0 var(--pad);background:linear-gradient(180deg,#151515,#0a0a0a);
    border:1px solid var(--ghost);font-size:var(--fs-data);letter-spacing:.15em;text-transform:uppercase;color:var(--dim)}
  #hud-top .brand{font-weight:700;letter-spacing:.2em;color:var(--dim);text-shadow:0 0 8px rgba(232,232,232,.30)}
  #hud-top .brand .brand-id{color:var(--acc-b)}
  #hud-top .sep{color:var(--faint)}
  #hud-top .item{color:var(--dim)}
  #hud-top .item b{color:var(--ink);font-weight:400}
  #hud-top .spacer{flex:1}
  #hud-top .live{color:var(--acc-b);white-space:nowrap}
  #hud-top .live::before{content:"";display:inline-block;width:6px;height:6px;margin-right:var(--grid);
    background:currentColor;border-radius:50%;animation:ledPulse 1.2s infinite}
  #hud-bot{display:flex;align-items:center;gap:var(--grid);padding:0 var(--pad);background:linear-gradient(180deg,#151515,#0a0a0a);
    border:1px solid var(--ghost);font-size:var(--fs-key);letter-spacing:.15em;text-transform:uppercase;
    color:var(--dim);font-variant-numeric:tabular-nums}
  #hud-bot .item b{color:var(--ink);font-weight:400}
  #hud-bot .item b.hot{color:var(--ink)}
  #hud-bot .spacer{flex:1}
  #hud-bot .prog{flex:0 0 220px;height:8px;background:#000;border:1px solid var(--ghost);position:relative;overflow:hidden}
  #hud-bot .prog .fill{height:100%;width:100%;background:var(--ink);transform-origin:left center;
    transform:scaleX(0);transition:transform .15s linear}
  #hud-bot .pct{color:var(--ink);font-weight:400}

  #scene{position:relative;overflow:hidden;background:var(--bg);--moon:68vmin;--mx:calc(50% - 34vmin);--my:4.8vmin}
  .w-head{display:flex;align-items:center;gap:var(--grid);white-space:nowrap;font-size:var(--fs-head);height:calc(var(--grid)*4);
    letter-spacing:.12em;text-transform:uppercase;color:var(--dim);padding:0 var(--pad);
    background:linear-gradient(180deg,#151515,#0a0a0a);border-bottom:1px solid var(--ghost);
    text-shadow:0 0 8px rgba(232,232,232,.30)}
  .w-head .led{width:6px;height:6px;border-radius:50%;color:var(--ink);background:currentColor;display:inline-block;flex:none;
    box-shadow:0 0 6px currentColor;animation:ledPulse 1.2s infinite}
  @keyframes ledPulse{0%,100%{opacity:1}50%{opacity:.35}}
  .work-panel{position:absolute;z-index:20;overflow:hidden;padding:var(--pad)}
  .work-panel>.w-head{margin:calc(-1*var(--pad)) calc(-1*var(--pad)) var(--grid)}
  #w-engine{left:calc(var(--grid)*2);top:calc(var(--grid)*2);width:calc(var(--grid)*44);height:calc(var(--grid)*56)}
  #w-term{left:calc(var(--grid)*2);bottom:calc(var(--grid)*2);width:calc(var(--grid)*44);height:calc(var(--grid)*19)}
  #w-bus{right:calc(var(--grid)*2);top:calc(var(--grid)*2);width:calc(var(--grid)*44);height:calc(100% - var(--grid)*4);display:flex;flex-direction:column}
  .terminal{padding:0;font-family:var(--font-mono);font-size:var(--fs-data);line-height:var(--row);
    letter-spacing:.045em;color:var(--dim);font-variant-numeric:tabular-nums;overflow:hidden}
  #term-core{height:calc(100% - var(--grid)*4)}
  #term-bus{flex:1;min-height:0}
  .terminal .ln{height:var(--row);color:var(--dim);white-space:nowrap}
  .terminal .ln.cmd,.terminal .ln.sys{color:var(--ink)}
  .terminal .ln.warn{color:var(--acc-b);font-weight:600}
  .terminal .ln.typing::after{content:"";display:inline-block;width:.5em;height:.95em;margin-left:.2em;
    background:var(--ink);vertical-align:-.1em}
  @keyframes lineIn{0%{opacity:0;transform:translateX(-.6vmin)}100%{opacity:1;transform:none}}

  /* The full-screen 10 px sweep band used to live here. It is gone: a bright bar
     walking the whole frame is a second focus by definition (R4 ③). The frame
     still never stands still, but it moves through the WINDOW (its progress,
     typed log, residence stopwatch) and the SYSTEM STREAM, which are the parts
     the beat is actually about. */
  /* 取景框只有一个。以前每一拍各有一套 --moon/--mx/--my，换拍时整块月球（limb、
     晨昏线、站点、弹阵点阵）一秒跳一个位置，而这块月亮在 1280×900 下占屏幕 24 %
     —— 换拍跳变里最贵的一块，也是硬切预算里唯一过不去的项。态势显示现在是常驻
     背景（只有取景推入在动），换拍只换窗口和标注。 */
  /* 换拍是交叉淡出，不是瞬切（R4 ②）：一条 320 ms 的 opacity 过渡，上一拍开始
     变淡的同时下一拍开始显影。全片唯一的整屏 fade 仍是 550C 自己的 #boot.fade。 */
  .ly{position:absolute;inset:0;opacity:0;pointer-events:none;transition:opacity .32s ease}
  .ly-map{opacity:0}
  .ly-final{transition-duration:.7s}
  #scene[data-phase="a2-cutaway"] .ly-cut{opacity:1}
  #scene[data-phase="b2-ignition"] .ly-flash{opacity:1}
  #scene[data-phase="b3-owned"] .ly-final{opacity:1}
  /* 一拍只换一件事：两件会抢焦点的场景层（月球、剖面）比窗口晚 250 ms 进来 ——
     于是窗口的 320 ms 淡入和图层自己的 320 ms 淡入不会落进同一个 500 ms 基准里。
     横幅与白闪不参与：它们不跟窗口同拍。 */
  #scene[data-phase="a2-cutaway"] .ly-cut{transition-delay:.25s}
  @media (max-aspect-ratio: 8/5){
    #scene[data-phase="a2-cutaway"] .ly-cut{transition-delay:.55s}
  }
  /* 让位（R4）：下一拍开始前 500 ms，本拍的场景层先自己淡出（180 ms）。换拍因此是
     "旧的走干净 → 新的进来"，不是两块图层和窗口在同一个 500 ms 基准里对撞。 */
  #scene.leaving .ly-cut{opacity:0;transition-delay:0s;transition-duration:.18s}

  /* ===== 角落参数块（skill §4 版式一：左上，双列对照，科学计数法） ===== */
  .w{position:relative;background:var(--panel);border:1px solid var(--ghost);box-shadow:inset 0 0 30px rgba(232,232,232,.035)}
  .w.work-panel{position:absolute}
  .w::before,.w::after{content:"";position:absolute;width:9px;height:9px;border-color:var(--dim);z-index:5;pointer-events:none}
  .w::before{top:-1px;left:-1px;border-top:1px solid;border-left:1px solid}
  .w::after{bottom:-1px;right:-1px;border-bottom:1px solid;border-right:1px solid}
  .param{contain:layout paint}
  .param .w-head .led{width:6px;height:6px;background:currentColor;display:inline-block;flex:none}
  .param .w-head .led.red{background:var(--dim)}
  .sect{margin:var(--grid) 0;font-size:var(--fs-key);letter-spacing:.26em;text-transform:uppercase;color:var(--faint)}
  .dt{display:flex;align-items:baseline;justify-content:space-between;gap:var(--grid);font-size:var(--fs-key);line-height:var(--row);letter-spacing:.05em;
    color:var(--dim);font-variant-numeric:tabular-nums}
  .dt .k{letter-spacing:.18em;white-space:nowrap}
  .dt .v{color:var(--ink);text-align:right;white-space:nowrap}
  .dt .v.hot{color:var(--ink)}

  .engine-pair{display:grid;grid-template-columns:1fr 1fr;gap:var(--grid);padding:0}
  .engine-card{min-width:0;border-bottom:1px solid var(--ghost);padding-bottom:var(--grid)}
  .engine-card .engine-name{color:var(--dim);font-family:var(--font-cjk);font-size:var(--fs-data);line-height:var(--row);
    letter-spacing:.08em;white-space:nowrap}
  .engine-name .en{display:block;font-size:var(--fs-note);font-family:var(--font-latin);letter-spacing:.18em}
  .engine-card svg{display:block;width:100%;height:calc(var(--grid)*10);margin:var(--grid) 0 0;overflow:hidden}
  .engine-card svg *{fill:none;stroke:var(--ink);stroke-width:1;vector-effect:non-scaling-stroke}
  .engine-card svg .dimline{stroke:var(--dim)}
  .engine-card svg .faintline{stroke:var(--faint)}
  .engine-card svg .ghostline{stroke:var(--ghost)}
  .engine-card svg .dashed{stroke-dasharray:4 5}
  .engine-card svg .earth-plume{opacity:0;transition:opacity .5s ease;
    filter:drop-shadow(0 0 8px rgba(var(--plume-glow),.75))}
  .engine-card svg .earth-plume .flame{fill:var(--plume);stroke:var(--plume);fill-opacity:.35}
  .engine-card svg .earth-plume .rays{fill:none;stroke:var(--plume)}
  #scene.ignited .earth-plume{opacity:1}
  .engine-ignition{height:var(--row);color:var(--acc-b);font-size:var(--fs-note);
    letter-spacing:.12em;white-space:nowrap;opacity:0;transition:opacity .42s ease}
  #scene.ignited .engine-ignition{opacity:1}
  .engine-breathe{transform-origin:50% 72%;animation:engineBreath 3.2s ease-in-out infinite}
  @keyframes engineBreath{0%,100%{transform:scale(1)}50%{transform:scale(1.018)}}
  .engine-data{margin-top:var(--grid);display:grid;grid-template-columns:1fr 1fr;gap:0 var(--grid)}
  .engine-data .dt.wide{grid-column:1/-1}
  .engine-spec{margin-top:var(--grid);padding-top:var(--grid);border-top:1px solid var(--ghost);
    display:grid;grid-template-columns:1fr 1fr;gap:0 var(--grid)}
  .engine-spec .dt{display:block}
  .engine-spec .v{display:block;text-align:left}
  .array-count{margin-top:var(--grid)}
  .array-track{height:1px;background:var(--ghost);margin:var(--grid) 0 0;display:flex}
  .array-track .earth-share{flex:10000;background:var(--dim)}
  .array-track .moon-share{flex:3;background:var(--ink);min-width:1px}
  .dt .k,.wp-row .k{font-size:var(--fs-key);color:var(--faint)}

  /* ===== 双语标签：灰白信息；红色只属于警告、点火、选定和 550W 标识 ===== */
  .lab{position:absolute;left:0;top:0;font-family:var(--font-cjk);white-space:nowrap;font-size:var(--fs-data);line-height:var(--row);
    letter-spacing:.16em;color:var(--dim);font-weight:600;opacity:0;transition:opacity .32s ease}
  .lab .en{font-family:var(--font-latin);font-size:var(--fs-note);letter-spacing:.24em;font-weight:500;margin-left:.5em}
  .lab .val{font-family:var(--font-mono);letter-spacing:.14em;color:var(--ink);margin-left:.55em}
  .lab::before{content:"";position:absolute;left:-1.1vmin;top:50%;width:.7vmin;height:1px;background:var(--faint)}
  .lab[data-layout-hidden]{opacity:0!important}
  .labs{position:absolute;inset:0;transition:opacity 1.2s linear}

  /* ===== 计划条（skill §4 版式三：右侧，三案并排，状态随叙事推进） ===== */
  .plan{display:grid;grid-template-columns:1fr;gap:var(--grid);margin:var(--grid) 0 0;
    padding:var(--pad);background:#030303;border:1px solid var(--ghost);transition:opacity .3s}
  .pi{position:relative;padding-left:calc(var(--grid)*2);font-family:var(--font-cjk);font-size:var(--fs-data);line-height:var(--row);letter-spacing:.14em;
    color:var(--faint);font-weight:600}
  .pi::before{content:"";position:absolute;left:0;top:.35em;width:.7vmin;height:.7vmin;
    border:1px solid var(--faint);background:transparent}
  .pi .en{display:block;font-family:var(--font-latin);font-size:var(--fs-note);letter-spacing:.24em;font-weight:500;
    color:var(--faint)}
  .pi .st{display:block;font-family:var(--font-mono);font-size:var(--fs-note);letter-spacing:.2em;color:var(--faint);
    font-variant-numeric:tabular-nums}
  .pi .num{color:var(--dim);font-weight:700}
  .pi[data-p="lunar"]{color:var(--dim)}
  .pi[data-p="lunar"] .en,.pi[data-p="lunar"] .st{color:var(--dim)}
  .pi[data-p="lunar"]::before{background:var(--dim);border-color:var(--dim)}
  .pi[data-p="lunar"] .num{color:var(--ink)}
  .pi.sel{color:var(--ink)}
  .pi.sel::before{background:var(--acc);border-color:var(--acc)}
  .pi.sel .en{color:var(--ink)}
  .pi.sel .st{color:var(--acc-b);border:1px solid var(--acc);display:inline-block;padding:0 .35em;transform:rotate(-2deg)}
  #scene[data-phase="b1-countdown"] .pi[data-p="lunar"],
  #scene[data-phase="b2-ignition"] .pi[data-p="lunar"]{color:var(--dim)}
  #scene[data-phase="b1-countdown"] .pi[data-p="lunar"] .st,
  #scene[data-phase="b2-ignition"] .pi[data-p="lunar"] .st{color:var(--dim)}

  /* ===== 月球：体积渐变 + 静态经纬 / 晨昏弧 / 刻度 / 测距尺 ===== */
  .moon{position:absolute;left:var(--mx);top:var(--my);width:var(--moon);height:var(--moon);clip-path:inset(0)}
  .moon svg{width:100%;height:100%;display:block;overflow:hidden}
  .moon::before{content:"";position:absolute;inset:8.958333%;border-radius:50%;
    background:radial-gradient(circle at 38% 34%,#1e1e1e,#0c0c0c 62%,#050505)}
  .moon>svg{position:relative}
  .moon .limb{fill:none;stroke:var(--ink);stroke-width:1;vector-effect:non-scaling-stroke}
  .moon .term{fill:none;stroke:var(--ghost);stroke-width:1;vector-effect:non-scaling-stroke}
  .moon .graticule{fill:none;stroke:var(--ghost);stroke-width:1;stroke-dasharray:3 6;vector-effect:non-scaling-stroke}
  .moon .reticle,.moon .scale-tick{fill:none;stroke:var(--ghost);stroke-width:1;vector-effect:non-scaling-stroke}
  .moon .scale-tick.major{stroke:var(--faint)}
  /* 400 user units map to 68vmin: this is --fs-data in SCREEN units, not a sixth
     typography level. The small camera push may magnify the whole map together. */
  .moon .scale-label{fill:var(--dim);font-family:var(--font-mono);font-size:calc(400px * 1.1 / 68);text-anchor:middle;dominant-baseline:middle}
  /* No geometry below owns a scan or path-drawing animation. */
  .moon .nightfill{fill:rgba(232,232,232,.055);stroke:none}
  .moon .night{opacity:.85}
  .moon .night line{stroke:var(--ghost);stroke-width:1}
  .surface-objects{position:absolute;inset:8.333333%}
  .earth .limb{fill:none;stroke:var(--dim);stroke-width:1}
  .earth .term{fill:none;stroke:var(--faint);stroke-width:1}
  .earth .planet-plume{opacity:0;transition:opacity .5s ease;
    filter:drop-shadow(0 0 8px rgba(var(--plume-glow),.75))}
  #scene.ignited .earth .planet-plume{opacity:1}
  .earth .planet-plume .flame{fill:url(#earth-plume-gradient);stroke:var(--plume);stroke-width:1}
  .earth .planet-plume .core{fill:var(--plume);stroke:none;opacity:.65}
  .range line,.range path{stroke:var(--faint);stroke-width:1;fill:none;vector-effect:non-scaling-stroke}
  .range circle{fill:var(--ink);stroke:none}
  .range text,.earth-label{fill:var(--dim);font-family:var(--font-mono);font-size:calc(400px * 1.1 / 68);letter-spacing:.5px}
  .range .distance{fill:var(--ink);text-anchor:middle}
  .sites{position:absolute;inset:0}
  .site{position:absolute;left:var(--x);top:var(--y);width:0;height:0}
  .site i.dot{position:absolute;left:-3px;top:-3px;width:6px;height:6px;background:var(--ink);
    border-radius:50%;transition:opacity .32s ease}
  .site .base{position:absolute;left:-2.1vmin;top:-2.1vmin;width:4.2vmin;height:4.2vmin;
    fill:none;stroke:var(--dim);stroke-width:1;filter:drop-shadow(0 0 3px rgba(232,232,232,.45))}
  .site.on .base{filter:drop-shadow(0 0 6px rgba(232,232,232,.45))}
  .site .base *{vector-effect:non-scaling-stroke}
  .site i.ring{position:absolute;left:-1.9vmin;top:-1.9vmin;width:3.8vmin;height:3.8vmin;
    border:1px solid var(--faint);border-radius:50%;opacity:0;transition:opacity .34s ease}
  .site.on i.ring{opacity:1}
  .site.on i.dot{background:var(--ink)}
  .site.tag-left .tag{left:auto;right:2.2vmin;text-align:right}
  .site .tag{position:absolute;left:2.2vmin;top:-.85vmin;white-space:nowrap;font-family:var(--font-cjk);
    font-size:var(--fs-data);letter-spacing:.14em;font-weight:600;color:var(--dim);opacity:0;transition:opacity .32s ease}
  .site .tag .en{font-family:var(--font-latin);font-size:var(--fs-note);letter-spacing:.24em;margin-left:.45em;font-weight:500}
  .site.on .tag{opacity:1}
  .site .idx{position:absolute;left:-.35vmin;top:-4.6vmin;font-family:var(--font-mono);font-size:var(--fs-data);
    letter-spacing:.1em;color:var(--ink);opacity:0;transition:opacity .32s ease}
  .site.on .idx{opacity:1}
  .site.done i.dot{background:var(--ink)}
  /* .site.armed i.ring.b（虚线外环）已删：③ 的删除清单里那个 dashed 环。站点"武装"
     状态由 tag 的 ARMED 文案与环的存在表达，不再加第二种线型。 */

  /* 弹阵：背景层，灰、低对比，不占主语（Q3） */
  .crater{position:absolute;left:var(--x);top:var(--y);width:var(--d);height:var(--d);
    transform:translate(-50%,-50%);border:1px dashed var(--faint);border-radius:50%;opacity:.9;
    transition:opacity .32s ease}
  .wh{position:absolute;inset:0;opacity:.62}
  /* 点阵是背景层（低对比、不占主语），但要真的看得见它在转：0.42vmin 的点在整屏
     缩到 96×54 之后是亚像素，探针读出来是"整块屏幕静止"。0.7vmin 仍然是背景密度，
     转动时却是实打实的位移。 */
  .wh i{position:absolute;left:var(--x);top:var(--y);width:.7vmin;height:.7vmin;background:var(--ghost);
    transform:translate(-50%,-50%);opacity:.34;transition:opacity .38s ease}
  .wh i.on{background:var(--faint)}
  .crater>svg{position:absolute;inset:0;width:100%;height:100%;fill:none;stroke:var(--ghost);stroke-width:1}
  .crater>svg *{vector-effect:non-scaling-stroke}
  /* 删掉的是「飘来飘去的线段」整族（R4 ③）：.arcs 的 dashed 链路弧与 drawLine 自绘、
     .relay 的虚线中继字形、.gauge 的 dashed 距离弧与读数、.jets 的两条 dasharray
     喷流。550C 的线只有 1px solid 的面板边框、行和一条波形，这里回到同一套词汇：
     下面那一条发动机剖面轮廓是全片唯一的实线图形。 */

  /* ===== 发动机剖面（skill §6 工程线框：fill:none, stroke:1, 层次靠 dasharray 与灰阶） ===== */
  .cut{position:absolute;left:52%;top:50%;transform:translate(-50%,-50%);height:88%;aspect-ratio:1/1.9;opacity:.65;
    animation:cutDrift 4.5s ease-in-out infinite}
  .cut svg{width:100%;height:100%;overflow:hidden}
  @media (max-aspect-ratio: 8/5){.cut{opacity:.55}}
  @media (max-width:1100px){.cut{opacity:.4}.ly-final{transition-duration:1.1s;transition-timing-function:linear}}
  .cut .shell{fill:none;stroke:var(--ink);stroke-width:1.5}
  .cut .inner{fill:none;stroke:var(--dim);stroke-width:1}
  .cut .hatch{fill:none;stroke:var(--ghost);stroke-width:1}
  #app svg *{vector-effect:non-scaling-stroke}

  /* ===== 550C popup geometry, four-layer shadows, title/status gradients.
     Amber remapped to neutral greys; semantic accent uses --acc-glow. ===== */
  #dim{position:fixed;inset:0;z-index:400;background:rgba(0,0,0,.15);opacity:0;pointer-events:none;
    transition:opacity .4s}
  #dim.show{opacity:1}
  .win-popup{position:fixed;z-index:500;min-width:640px;max-width:min(980px,94vw);background:var(--win);font-variant-numeric:tabular-nums;
    border:1px solid var(--faint);box-shadow:0 24px 70px rgba(0,0,0,.78),0 0 0 1px rgba(0,0,0,.9),
      0 0 50px rgba(232,232,232,.07),inset 0 0 24px rgba(232,232,232,.02);opacity:0;transform:scale(.9) translateY(-6px);
    transition:opacity .32s ease, transform .32s cubic-bezier(.2,1.05,.4,1);overflow:hidden;pointer-events:none}
  .win-popup.show,.popup .win-popup.show{opacity:1;transform:scale(1) translateY(0);pointer-events:auto}
  .win-popup.closing{opacity:0;transform:scale(.94) translateY(-4px);transition-duration:.16s}
  @media (max-aspect-ratio: 8/5){
    .win-popup{width:calc(100vw - 80vmin);min-width:0;max-width:calc(100vw - 80vmin);
      transition:opacity .6s linear,transform .4s cubic-bezier(.2,1.05,.4,1)}
    .win-popup.closing{transition-duration:.16s}
  }
  .win-popup.danger{border-color:var(--faint)}
  /* 550C 的五个停靠位：tr / tl / l / br / center，一个窗口一位，不挤同一角。 */
  .wp-pos-tr{right:40vmin;top:5.6vmin}
  .wp-pos-tl{left:40vmin;top:5.6vmin}
  .wp-pos-l{left:calc(43vmin + 20px);top:38%}
  .wp-pos-br{right:40vmin;bottom:4.8vmin}
  .wp-pos-center{left:50%;top:42%;translate:-50% 0}
  .wp-title{display:flex;align-items:center;gap:var(--grid);padding:var(--pad);background:linear-gradient(180deg,#151515,#0a0a0a);
    border-bottom:1px solid var(--faint);font-size:var(--fs-data);letter-spacing:.12em;color:var(--dim);user-select:none;white-space:nowrap}
  .win-popup.danger .wp-title{border-bottom-color:var(--faint);color:var(--ink)}
  .wp-title .wp-name{text-shadow:0 0 8px rgba(232,232,232,.30)}
  .wp-title .wp-ico{width:14px;height:14px;flex:none;display:flex;align-items:center;justify-content:center;font-size:var(--fs-data)}
  .wp-title .wp-name{flex:1;font-weight:500;letter-spacing:.16em;text-transform:uppercase}
  .wp-title .wp-controls{display:flex;gap:6px;color:var(--faint);opacity:.8}
  .wp-body{padding:var(--pad);font-size:var(--fs-body);line-height:var(--row);color:var(--ink);max-height:56vh;overflow:auto}
  .popup[data-p="meter"] .wp-body{padding:max(16px,var(--pad))}
  .wp-row{display:grid;align-items:baseline;grid-template-columns:auto 1fr;gap:var(--grid);padding:0;font-size:var(--fs-body);line-height:var(--row);
    font-variant-numeric:tabular-nums;border-bottom:1px dotted var(--ghost)}
  .wp-row:last-child{border-bottom:none}
  .wp-row .k{color:var(--faint);letter-spacing:.08em;text-transform:uppercase;font-size:var(--fs-key);white-space:nowrap}
  .wp-row .v{color:var(--ink);text-align:right;letter-spacing:.02em;font-size:var(--fs-body);white-space:nowrap}
  .wp-row .v.warn{color:var(--acc-b)}
  .wp-row .v.bad{color:var(--acc-b);font-weight:700}
  .wp-div{height:1px;background:var(--ghost);margin:var(--grid) 0}
  .wp-note{margin-top:var(--grid);font-size:var(--fs-note);line-height:var(--row);letter-spacing:.04em;color:var(--dim);text-wrap:balance}
  .wp-log{padding:0;font-size:var(--fs-data);line-height:var(--row);letter-spacing:.02em;font-variant-numeric:tabular-nums;white-space:nowrap}
  .wp-log .ll{color:var(--dim)}
  .wp-log .ll.sys{color:var(--ink)}
  .wp-log .ll.warn{color:var(--acc-b)}
  .wp-prog{height:8px;background:#000;border:1px solid var(--ghost);overflow:hidden}
  .wp-prog .f{height:100%;background:var(--ink);width:100%;transform-origin:left center;
    transform:scaleX(0);transition:transform .9s ease-out}
  .wp-meter{display:flex;align-items:baseline;flex-wrap:wrap;gap:var(--grid);padding:var(--grid) 0;font-variant-numeric:tabular-nums}
  .wp-meter .big{min-width:0;font-size:var(--fs-big);color:var(--ink);letter-spacing:.02em;text-shadow:0 0 14px rgba(232,232,232,.45)}
  .popup[data-p="meter"] .wp-meter .big{
    font-size:min(var(--fs-big),7.2vmin,calc((100vw - 80vmin - 48px) / 7));line-height:1.15}
  #b-count{color:var(--acc-b);text-shadow:0 0 14px rgba(var(--acc-glow),.8)}
  .wp-meter .unit{min-width:0;font-size:var(--fs-data);color:var(--dim);letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}
  .win-popup.danger .wp-meter .big{color:var(--ink)}
  .wp-status{display:flex;align-items:baseline;gap:var(--grid);padding:var(--pad);background:linear-gradient(180deg,#151515,#0a0a0a);
    border-top:1px solid var(--faint);font-size:var(--fs-key);letter-spacing:.14em;text-transform:uppercase;
    color:var(--faint);font-variant-numeric:tabular-nums}
  .win-popup.danger .wp-status{border-top-color:var(--faint)}
  .wp-status .spacer{flex:1}
  .wp-elapsed{white-space:nowrap;min-width:5em;color:var(--dim)}
  .wp-alert-strip{height:2px;width:100%;background:var(--acc);opacity:.85}

  /* ===== 倒计时（诚实时钟，等宽 tabular-nums，字重拉满） =====
     b1 的整屏压暗是一层真的叠加（原来那个 .dim 挂在 .ly-flash 里面，父层 opacity 0，
     从来没显过），用 320 ms 过渡爬上去，不再是一条 2.4 s 的动画：全场只该有一个焦点
     （居中窗口的读数），背景只要安静地退后一档。 */
  .dim{position:absolute;inset:0;z-index:300;background:rgba(0,0,0,.58);opacity:0;
    transition:opacity .8s ease;pointer-events:none}
  #scene[data-phase="b1-countdown"] .dim{opacity:.35}
  .flash{position:absolute;inset:0;background:#fff;opacity:0}
  /* 点火那一拍底层的 6 % 白洗只在"允许动效"的档位存在：reduced 档里它是常驻的整屏
     亮暗（进出都是一刀），而 skill §5 的 reduced 口径是"白闪整块换成静态印记"。 */
  @media (prefers-reduced-motion: no-preference){
    #app[data-phase="b2-ignition"] .flash{opacity:.06}
  }
  /* 白闪盖在窗口之上（窗口的 .win-popup 是 z-index 500，而且 popup 是挂到 #scene
     末尾的）：倒数窗口比它那一拍多活 200 ms，读数写完 T-00:00.000 才退场。 */
  .ly-flash{z-index:600}
  .stamp{position:absolute;left:50%;top:calc(var(--grid)*8);transform:translateX(-50%) rotate(-12deg);z-index:304;
    padding:.9vmin 2.2vmin;border:2px solid var(--acc);color:var(--acc-b);font-family:var(--font-cjk);
    font-size:var(--fs-sub);font-weight:700;letter-spacing:.3em;opacity:0;transition:opacity .32s ease}
  .stamp .en{font-family:var(--font-latin);font-size:var(--fs-data);letter-spacing:.4em;font-weight:500;margin-left:.6em}
  #scene[data-phase="b2-ignition"] .stamp.ignition{opacity:1}
  /* The skill's rule: under reduced motion the flash is dropped and the SAME
     event is announced by a static mark — 「引爆 DETONATION」 is that mark, and
     it is the only place that wording appears. In the normal cut the ignition
     is announced by the flash itself, and the static mark reads 点火 IGNITION. */
  @media (prefers-reduced-motion: reduce){
    #scene[data-phase="b2-ignition"] .stamp.ignition{opacity:0}
    #scene[data-phase="b2-ignition"] .stamp.substitute{opacity:1}
  }

  /* ===== 结尾横幅：550C #final 的琥珀色装置；只保留宽带的 min-width 例外。
     光柱的位置用 transform 代替布局属性，视觉行程与 550C 相同。 ===== */
  .w-final{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);z-index:800;padding:52px 110px;min-width:min(62vw,106vmin);
    background:#0a0805;border-top:1px solid var(--amber);border-bottom:1px solid var(--amber);
    box-shadow:0 0 80px rgba(232,160,32,.55),0 0 180px rgba(232,160,32,.22),
      inset 0 0 80px rgba(232,160,32,.08);
    color:var(--amber-b);font-size:clamp(30px,4.4vw,58px);letter-spacing:.26em;
    text-align:center;text-shadow:0 0 14px rgba(232,160,32,.95),0 0 40px rgba(232,160,32,.6);white-space:nowrap;
    font-weight:500;clip-path:inset(0 50% 0 50%);opacity:0;
    transition:clip-path .48s cubic-bezier(.7,0,.2,1), opacity .2s ease}
  .w-final.show{opacity:1;clip-path:inset(0 0 0 0)}
  /* Normal completion only: close the same clip while fading its amber glow.
     Entry values stay identical to 550C; skip/shared teardown stays untouched. */
  :host(.dsh550w-complete.dsh550c-out) .w-final.show{
    clip-path:inset(0 50% 0 50%);transition:clip-path 1.8s linear,opacity 1.8s linear}
  /* The map retires horizontally with the banner after 15.45s, rather than
     dropping its whole low-contrast moon volume into black in one lookback. */
  :host(.dsh550w-complete.dsh550c-out) #app #scene .ly-map{
    opacity:0;transition:opacity 3s linear}
  :host(.dsh550w-complete.dsh550c-out) #app .moon{
    clip-path:inset(0 50% 0 50%);transition:clip-path 2.1s linear}
  @media (max-width:1100px){
    :host(.dsh550w-complete.dsh550c-out) #app #scene .ly-map{transition-duration:2.6s}
  }
  .w-final::before,.w-final::after{content:"";position:absolute;top:-2px;bottom:-2px;width:2px;
    background:var(--amber-b);box-shadow:0 0 20px 4px rgba(232,160,32,.9);opacity:0;pointer-events:none}
  .w-final::before{left:50%}
  .w-final::after{right:50%}
  .w-final.show::before{animation:edgeLeft .48s cubic-bezier(.7,0,.2,1) forwards}
  .w-final.show::after{animation:edgeRight .48s cubic-bezier(.7,0,.2,1) forwards}
  @keyframes edgeLeft{0%{transform:translateX(0);opacity:1}90%{transform:translateX(calc(-1 * min(31vw,53vmin)));opacity:1}100%{transform:translateX(calc(-1 * min(31vw,53vmin)));opacity:0}}
  @keyframes edgeRight{0%{transform:translateX(0);opacity:1}90%{transform:translateX(min(31vw,53vmin));opacity:1}100%{transform:translateX(min(31vw,53vmin));opacity:0}}

  /* ===== 拍内可见性（每拍只开自己那几件；换拍由 .ly/.lab 的 320 ms 过渡交叉淡出） ===== */
  .popup{position:absolute;inset:0;pointer-events:none}
  .popup .win-popup{opacity:0}
  #scene[data-phase="a1-moonrise"] .lab[data-p~="a1-moonrise"],
  #scene[data-phase="a2-cutaway"] .lab[data-p~="a2-cutaway"],
  #scene[data-phase="a3-link"] .lab[data-p~="a3-link"],
  #scene[data-phase="a4-armed"] .lab[data-p~="a4-armed"],
  #scene[data-phase="b1-countdown"] .lab[data-p~="b1-countdown"],
  #scene[data-phase="b2-ignition"] .lab[data-p~="b2-ignition"]{opacity:1}

  /* ===== 运动：每一拍至少两层在动（主体 + 背景/数据），但**没有一个循环短于 3 s，
     也没有一个循环在来回摆不透明度**（R4 ②）。短于 2.5 s 的呼吸/扫描全族已删：
     ringPulse .7s、beamFlow .34/.6s、beamPulse 1.1s、coilCharge 1.1s、fieldPulse 1.2s、
     窗口/参数纵向扫描、dataSweep 1.8s、planScan 1.6s、girtTighten 1.5/1.8s，
     外加整屏横带 .sweep + frameSweep 2.6s。留下的全是 transform，周期 ≥3.2 s。
     只动 transform / opacity / filter，不动 width/height/top/left。 ===== */
  @keyframes fieldSpin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}
  @keyframes fieldPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.12)}}
  @keyframes camPush{0%{transform:scale(1)}100%{transform:scale(1.06)}}
  @keyframes cutDrift{0%,100%{transform:translate(-50%,-52.6%)}50%{transform:translate(-50%,-47.4%)}}
  @keyframes termSweep{0%{transform:translateX(-46px)}50%{transform:translateX(46px)}100%{transform:translateX(-46px)}}
  @keyframes pushIn{0%{transform:translate(-1.1%,-0.5%) scale(1)}50%{transform:translate(1.1%,0.5%) scale(1.045)}100%{transform:translate(-1.1%,-0.5%) scale(1.09)}}
  @keyframes ringSweep{0%,100%{transform:scale(.78)}50%{transform:scale(1.16)}}
  @keyframes selPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.32)}}

  /* a1-moonrise：静态经纬/晨昏线/站点底盘，仅沿用原有取景推入。
     取景推入挂在元素上，不挂在 [data-phase] 上：按拍声明的话，拍一换动画就被撤掉，
     月球会从推入到一半的位置"啪"地弹回原样 —— 那是一处真实的换拍跳变。现在它是
     一条常驻动画，窗口打开时由 ④ 的 animation-play-state 冻结。 */
  .moon{animation:pushIn 4.5s ease-out both}
  .ly-map{animation:camPush 4.5s ease-out both}
  .site i.ring{animation:none}
  .site:nth-child(2) i.ring{animation-delay:.4s}
  .site:nth-child(3) i.ring{animation-delay:.8s}
  .wh{animation:fieldSpin 5s linear infinite, fieldPulse 3.4s ease-in-out infinite}
  .moon .nightwrap{animation:none}

  /* a2-cutaway：只有剖面在慢慢漂（transform，4.5 s），轮廓是一条实线，不自绘 */

  /* 计划条：只留选定印记的缓慢呼吸（transform，3.4 s） */
  .plan .pi.sel::before{animation:selPulse 3.4s ease-in-out infinite}

  /* a4-armed / b1-countdown：相机继续推入（.moon 的 pushIn 与 .ly-map 的 camPush
     都是常驻动画，见上文）。 */

  /* ④ 焦点预算：屏幕上有窗口时冻结的是**相机与构图**（取景推入、剖面漂移、
     标签/参数块的循环），窗口成为这一拍唯一的焦点，背景由 #dim 再压一档。
     窗口自己用驻留秒表、逐行日志、驻留进度表达活性，不用装饰性纵向扫描。 */
  #scene.win .ly-map,#scene.win .ly-cut,#scene.win .moon,#scene.win .cut{animation-play-state:paused}
  #scene[data-phase="b3-owned"] .ly-map,#scene[data-phase="b3-owned"] .moon{animation-play-state:paused}

  /* 连续动画的元素升为合成层：不升的话每帧都要重绘整块面板/整块场景，
     实测这一项值 0.4–0.8 个百分点。 */
  .wh,.ly-map,.cut{will-change:transform}
  .wp-status .wp-prog{flex:0 0 88px;height:3px;border-width:1px;margin:0}
  .wp-status .wp-prog .f{transition:transform .18s linear}

  /* Reduced motion. 550C has no such block because its whole reduced-motion story
     is the 简易 档位 — the app face never mounts. 550W's app face is live in both
     档位 when the user explicitly asked for 完整, so the frame has to stop moving
     on its own: the white flash (handled in show.js, it is a JS beat), the glow,
     the CRT flicker. Hard cuts, counters, the window appearing/disappearing and
     the one-by-one deployment all stay — they are the film's grammar, not
     decoration. */
  @media (prefers-reduced-motion: reduce){
    #hud-top .live::before{animation:none;opacity:1}
    .boot-text .cursor{animation:none;opacity:1}
    #logo.finished .white,#logo.finished .red{animation:none}
    :host::before,:host::after{opacity:0}
    /* Every continuous loop in this machine is a CSS animation, so one rule turns
       them all off — the skill's reduced-motion rule keeps only hard cuts,
       counters and the discrete one-by-one deployment. */
    #app *,#boot *{animation:none!important}
    /* 换拍回到硬切：过渡整条关掉，窗口的出现/消失也变成一刀切。 */
    .ly,.lab,.labs,.param,.plan,.pi,.pi::before,.site i.ring,.site i.dot,.site .tag,.site .idx,
    .wh i,.moon,.crater,.stamp,.w-final,.dim,.win-popup,.popup .win-popup,
    .planet-plume,.earth-plume,.engine-ignition,
    .prog .fill,.wp-prog .f{transition:none!important}
    #hud-top,#hud-bot,.work-panel,.ly-map,.labs{transition:none!important}
  }
`

/**
 * The warhead array: 72 sample points on four concentric rings inside Campanus
 * Crater. It is a *sample*, not a census — the readout keeps printing 3,751 (the
 * film's number) because that is the figure the array owns. Generated here so the
 * markup stays readable and the same list can drive the ring-by-ring lighting.
 */
function warheadRingMarkup() {
  const rings = [
    { count: 14, radius: 18 },
    { count: 18, radius: 29 },
    { count: 20, radius: 40 },
    { count: 20, radius: 48 },
  ]
  const out = []
  let index = 0
  for (const ring of rings) {
    for (let i = 0; i < ring.count; i++) {
      const angle = (i / ring.count) * Math.PI * 2 + ring.radius * 0.07
      const x = 50 + Math.cos(angle) * ring.radius
      const y = 50 + Math.sin(angle) * ring.radius
      out.push(
        '<i style="--x:' + x.toFixed(2) + '%;--y:' + y.toFixed(2) + '%;--i:' + index++ + '"></i>',
      )
    }
  }
  return out.join('')
}

const WARHEAD_DOTS = warheadRingMarkup()

/** Static instrument geometry: angles and ring spacing are drawing coordinates,
 * not story telemetry. No timer, path drawing or scanning owns these lines. */
const MOON_SCALE = Array.from({ length: 72 }, (_, i) => {
  const angle = i * 5 * Math.PI / 180
  const major = i % 6 === 0
  const point = (radius) => [200 + Math.sin(angle) * radius, 200 - Math.cos(angle) * radius].map(n => n.toFixed(2))
  const a = point(171.6667), b = point(171.6667 + (major ? 6.6667 : 2.5)), label = point(187.5)
  return `<line class="scale-tick ${major ? 'major' : ''}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>` +
    (major ? `<text class="scale-label" x="${label[0]}" y="${label[1]}">${i * 5}</text>` : '')
}).join('')
// One 400-unit frame: Moon (200,200), Earth (60,354.1667).
// The ruler endpoints are the two actual centres, not an ornamental bracket.
const RANGE_550W = (() => {
  const earth = [60,354.1667], moon = [200,200]
  const dx = moon[0]-earth[0], dy=moon[1]-earth[1], length=Math.hypot(dx,dy)
  const ticks=Array.from({length:19},(_,i)=>{
    const x=earth[0]+dx*i/18,y=earth[1]+dy*i/18,n=i%3===0?6.6667:2.5
    return `<line x1="${x.toFixed(2)}" y1="${y.toFixed(2)}" x2="${(x-dy/length*n).toFixed(2)}" y2="${(y+dx/length*n).toFixed(2)}"/>`
  }).join('')
  return `<g class="range"><path id="distance-line" d="M60 354.1667 L200 200"/>${ticks}<circle class="endpoint earth-end" cx="60" cy="354.1667" r="2.5"/><circle class="endpoint moon-end" cx="200" cy="200" r="2.5"/><text class="distance" x="130" y="265.8333">3.84E8 M</text></g>`
})()
const SITE_BASE = `<svg class="base" viewBox="0 0 60 60" aria-hidden="true"><circle cx="30" cy="30" r="22"/><path d="M22 30 H38 M30 22 V38"/>${Array.from({length:6},(_,i)=>`<path transform="rotate(${i*60} 30 30)" d="M30 2 V8"/>`).join('')}</svg>`
const ARRAY_RINGS = `<svg viewBox="0 0 100 100" aria-hidden="true">${[18,29,40,48].map(r=>`<circle cx="50" cy="50" r="${r}"/><path d="M${50+r} 47 V53"/>`).join('')}<path d="M50 50 H98"/></svg>`

/**
 * The full-mode surface: top bar, master situation display (moon map / engine
 * section / countdown / banner as hard-cut layers — the MOSS card was cut in R1,
 * 结尾停在「接入成功」), the three persistent information layers (corner data
 * block, object labels, project strip), the rolling system stream, and the five
 * windows (which show.js attaches per beat).
 */
const APP_550W = `
<div id="app" data-phase="a1-moonrise">
  <div id="hud-top">
    <span class="brand">◢ <span class="brand-id">550W</span> // LUNAR OVERRIDE</span>
    <span class="sep">│</span>
    <span class="item">MODE <b>FULL</b></span>
    <span class="item">JURISDICTION <b>LUNAR ENGINE CLUSTER</b></span>
    <span class="item">SESSION <b id="h-session">ID/CN A02 EE</b></span>
    <span class="spacer"></span>
    <span class="item">TIME <b id="h-time">00:00:00</b></span>
    <span class="sep">│</span>
    <span class="item live">REC</span>
  </div>

  <div id="scene" data-phase="a1-moonrise">
    <div class="ly ly-map">
      <div class="moon">
        <svg class="instrument" viewBox="0 0 400 400" aria-hidden="true">
          <defs>
            <clipPath id="moonClip"><circle cx="200" cy="200" r="164.1667"/></clipPath>
            <linearGradient id="earth-plume-gradient" gradientUnits="userSpaceOnUse" x1="60" y1="375" x2="60" y2="400">
              <stop offset="0" stop-color="var(--plume)" stop-opacity=".78"/>
              <stop offset="1" stop-color="var(--plume)" stop-opacity=".08"/>
            </linearGradient>
          </defs>
          <circle class="limb moon-disc" cx="200" cy="200" r="164.1667"/>
          <g clip-path="url(#moonClip)">
            <ellipse class="graticule" cx="200" cy="200" rx="55" ry="164.1667"/>
            <ellipse class="graticule" cx="200" cy="200" rx="112.5" ry="164.1667"/>
            <ellipse class="graticule" cx="200" cy="200" rx="164.1667" ry="54.1667"/>
            <ellipse class="graticule" cx="200" cy="200" rx="164.1667" ry="110"/>
            <path class="term" transform="rotate(-28 200 200)" d="M200 35.8333 A78.3333 164.1667 0 0 1 200 364.1667"/>
          </g>
          <path class="reticle" d="M25 200 H375 M200 25 V375 M195 195 L205 205 M205 195 L195 205"/>
          ${MOON_SCALE}
          <g class="earth">
            <g class="planet-plume"><path class="flame" d="M54 375 L66 375 L74 399 L46 399 Z"/><path class="core" d="M57 376 L63 376 L66 399 L54 399 Z"/></g>
            <circle class="limb earth-disc" cx="60" cy="354.1667" r="23.3333"/><path class="term" d="M60 330.8333 A15 23.3333 0 0 1 60 377.5"/>
          </g>
          ${RANGE_550W}
          <text class="earth-label" x="112" y="383">［地球］EARTH</text>
        </svg>
        <div class="surface-objects">
        <div class="sites">
          <div class="site on" data-site="01" style="--x:33%;--y:41%">
            ${SITE_BASE}<i class="ring"></i><span class="idx">01</span>
            <span class="tag">［卫星发动机 01］<span class="en">LUNAR ENGINE 01</span></span>
          </div>
          <div class="site on tag-left" data-site="02" style="--x:57%;--y:27%">
            ${SITE_BASE}<i class="ring"></i><span class="idx">02</span>
            <span class="tag">［卫星发动机 02］<span class="en">LUNAR ENGINE 02</span></span>
          </div>
          <div class="site on tag-left" data-site="03" style="--x:52%;--y:66%">
            ${SITE_BASE}<i class="ring"></i><span class="idx">03</span>
            <span class="tag">［卫星发动机 03］<span class="en">LUNAR ENGINE 03</span></span>
          </div>
        </div>
        <div class="crater" style="--x:67%;--y:64%;--d:30%">
          ${ARRAY_RINGS}
          <div class="wh" id="whField">${WARHEAD_DOTS}</div>
        </div>
        </div>
      </div>
    </div>

    <div class="ly ly-cut">
      <div class="cut">
        <svg viewBox="0 0 210.5263 400" aria-hidden="true">
          <path class="shell" d="M67.3684 9.8246 L143.1579 9.8246 L158.5965 51.9298 L51.9298 51.9298 Z"/>
          <path class="shell" d="M51.9298 51.9298 L158.5965 51.9298 L165.6140 144.5614 L44.9123 144.5614 Z"/>
          <path class="hatch" d="M44.9123 64.5614 L165.6140 98.2456 M44.9123 82.8070 L165.6140 116.4912 M44.9123 101.0526 L165.6140 134.7368"/>
          <path class="shell" d="M44.9123 144.5614 L165.6140 144.5614 L130.5263 181.0526 L80 181.0526 Z"/>
          <ellipse class="inner" cx="105.2632" cy="181.0526" rx="23.8596" ry="5.6140"/>
          <path class="shell" d="M80 181.0526 L130.5263 181.0526 C165.6140 224.5614 183.8596 266.6667 188.0702 301.7544 L22.4561 301.7544 C26.6667 266.6667 44.9123 224.5614 80 181.0526 Z"/>
          <path class="inner" d="M105.2632 183.8596 L105.2632 300.3509"/>
          <ellipse class="shell" cx="105.2632" cy="304.5614" rx="82.8070" ry="10.5263"/>
          <ellipse class="shell" cx="105.2632" cy="314.3860" rx="40.7018" ry="5.6140"/>
        </svg>
      </div>
    </div>

    <div id="dim"></div>
    <div class="dim"></div>

    <div class="ly ly-flash">
      <div class="flash"></div>
      <div class="stamp ignition">［点火］<span class="en">IGNITION</span></div>
      <div class="stamp substitute">［引爆］<span class="en">DETONATION</span></div>
    </div>

    <div class="ly ly-final">
      <div class="w-final">接入成功</div>
    </div>

    <div id="w-engine" class="param w work-panel">
      <div class="w-head"><span class="led"></span>［发动机］ENGINE SCHEMATICS</div>
      <div class="engine-pair engine-breathe">
        <div class="engine-card">
          <div class="engine-name">［行星发动机］<span class="en">EARTH ENGINE</span></div>
          <svg viewBox="0 0 160 110" aria-hidden="true">
            <path d="M49 12 H111 L128 72 H32 Z"/><path class="dimline" d="M42 44 H118 M36 65 H124"/>
            <path class="faintline" d="M61 12 L55 72 M80 12 V72 M99 12 L105 72"/>
            <path class="dashed ghostline" d="M46 78 L30 108 M65 78 L58 108 M95 78 L102 108 M114 78 L130 108"/>
            <g class="earth-plume"><path class="flame" d="M68 78 L92 78 L116 108 L44 108 Z"/>
              <path class="dashed rays" d="M46 78 L30 108 M65 78 L58 108 M95 78 L102 108 M114 78 L130 108"/></g>
          </svg>
          <div class="engine-ignition">［点火］IGNITION</div>
        </div>
        <div class="engine-card">
          <div class="engine-name">［月球行星发动机］<span class="en">LUNAR ENGINE</span></div>
          <svg viewBox="0 0 160 110" aria-hidden="true">
            <path d="M24 76 L42 24 L60 76 Z M62 76 L80 24 L98 76 Z M100 76 L118 24 L136 76 Z"/>
            <path class="dimline" d="M15 82 H145 M27 89 H133"/><path class="faintline" d="M34 45 H50 M72 45 H88 M110 45 H126"/>
            <path class="dashed ghostline" d="M34 92 L28 108 M48 92 L46 108 M73 92 L71 108 M87 92 L89 108 M112 92 L114 108 M126 92 L132 108"/>
          </svg>
        </div>
      </div>
      <div class="engine-data">
        <div class="dt"><span class="k">DIST</span><span class="v">3.84E8 M</span></div>
        <div class="dt"><span class="k">DELAY</span><span class="v">1.28 S</span></div>
        <div class="dt"><span class="k">MASS ⊕</span><span class="v">5.97E24 KG</span></div>
        <div class="dt"><span class="k">MASS ☾</span><span class="v">7.35E22 KG</span></div>
        <div class="dt"><span class="k">DENS ⊕</span><span class="v">5.515</span></div>
        <div class="dt"><span class="k">DENS ☾</span><span class="v">3.346</span></div>
        <div class="dt"><span class="k">RAD ☾</span><span class="v">1.74E6 M</span></div>
      </div>
      <div class="engine-spec">
        <div class="dt"><span class="k">HEIGHT</span><span class="v">11 KM</span></div>
        <div class="dt"><span class="k">BODY ⌀</span><span class="v">20–30 KM</span></div>
        <div class="dt"><span class="k">BASE ⌀</span><span class="v">50–60 KM</span></div>
        <div class="dt"><span class="k">THRUST SUM</span><span class="v">1.5E14 TON</span></div>
      </div>
      <div class="array-count"><div class="dt"><span class="k">COUNT ⊕/☾</span><span class="v"><span id="earth-engine-count">10,000</span> / 3</span></div>
        <div class="array-track"><i class="earth-share"></i><i class="moon-share"></i></div></div>
    </div>

    <div class="labs">
      <div class="lab" data-p="a1-moonrise" data-anchor=".54,.65">［月球］<span class="en">MOON</span></div>
      <div class="lab" data-p="a1-moonrise a3-link a4-armed b1-countdown" data-anchor=".48,.72">［核弹分布］<span class="en">NUCLEAR WARHEAD DISTRIBUTION</span></div>
      <div class="lab" data-p="a1-moonrise a4-armed" data-anchor=".46,.28">［月球发动机集群］<span class="en">LUNAR ENGINE CLUSTER</span></div>
      <div class="lab" data-p="a3-link b1-countdown" data-anchor=".50,.15">［空间站 · 中继］<span class="en">SPACE STATION RELAY</span></div>
      <div class="lab" data-p="a2-cutaway" data-anchor=".60,.45">［磁约束线圈 ×4］<span class="en">MAGNETIC COIL ×4</span></div>
      <div class="lab" data-p="a2-cutaway" data-anchor=".63,.65">［喷口］<span class="en">NOZZLE BELL</span></div>
      <div class="lab" data-p="b1-countdown" data-anchor=".50,.80">［点火窗口］<span class="en">IGNITION WINDOW</span></div>
    </div>

    <div id="w-term" class="w work-panel">
      <div class="w-head"><span class="led"></span>［核心终端］550W CORE TERMINAL</div>
      <div class="terminal" id="term-core"></div>
    </div>

    <div id="w-bus" class="w work-panel">
      <div class="w-head"><span class="led"></span>［控制总线］CONTROL BUS</div>
      <div class="terminal" id="term-bus" data-fingerprint="ID/CN A02 EE"></div>
      <div class="plan">
        <div class="pi gone" data-p="ark">［方舟计划］<span class="en">THE ARK PROJECT</span><span class="st">否决 REJECTED</span></div>
        <div class="pi" data-p="lunar">［逐月计划］<span class="en">THE LUNAR PROJECT</span><span class="st"><span class="num">3,751</span> 弹头 WARHEADS</span></div>
        <div class="pi sel" data-p="mountain">［移山计划］<span class="en">THE MOVING MOUNTAIN PROJECT</span><span class="st">选定 SELECTED</span></div>
      </div>
    </div>

    <div class="popup" data-p="target">
      <div class="win-popup wp-pos-tr">
        <div class="wp-title"><span class="wp-ico">◎</span><span class="wp-name">［目标识别］TARGET ACQUISITION</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-body">
          <div class="wp-row"><span class="k">TARGET</span><span class="v">月球发动机集群</span></div>
          <div class="wp-row"><span class="k">WARHEAD</span><span class="v">3,751</span></div>
          <div class="wp-row"><span class="k">PROJECT</span><span class="v">逐月计划 · 2058</span></div>
          <div class="wp-note">我在找月球上那三台发动机：先把目标认出来，再决定从哪一步接管。</div>
        </div>
        <div class="wp-status"><span>ACQUIRING</span><span class="spacer"></span><span class="wp-clock">--:--:--</span></div>
      </div>
    </div>

    <div class="popup" data-p="meter">
      <div class="win-popup wp-pos-center">
        <div class="wp-title"><span class="wp-ico">◆</span><span class="wp-name">［点火窗口］DETONATION WINDOW</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-body">
          <div class="wp-meter"><span class="big" id="b-count">T-00:02.400</span><span class="unit">/ 点火窗口 IGNITION</span></div>
          <div class="wp-row"><span class="k">WARHEAD</span><span class="v">3,751 / 3,751</span></div>
          <div class="wp-row"><span class="k">RELAY</span><span class="v">NAVIGATOR · 1.28 S</span></div>
          <div class="wp-note">我在等点火窗口。T-00:02.400 到 T-00:00.000 是真实时间，读数不加速、不取整。</div>
        </div>
        <div class="wp-status"><span>HOLDING</span><span class="spacer"></span><span class="wp-clock">--:--:--</span></div>
      </div>
    </div>

    <div class="popup" data-p="cut">
      <div class="win-popup wp-pos-tl">
        <div class="wp-title"><span class="wp-ico">▣</span><span class="wp-name">［一号月球发动机 · 剖面］LUNAR ENGINE 01 · SECTION</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-body">
          <div class="wp-row"><span class="k">CLASS</span><span class="v">卫星发动机 LUNAR ENGINE</span></div>
          <div class="wp-row"><span class="k">HEIGHT</span><span class="v">11 KM</span></div>
          <div class="wp-row"><span class="k">BODY ⌀</span><span class="v">20–30 KM</span></div>
          <div class="wp-row"><span class="k">BASE ⌀</span><span class="v">50–60 KM</span></div>
          <div class="wp-row"><span class="k">COUNT</span><span class="v">3</span></div>
          <div class="wp-div"></div>
          <div class="wp-row"><span class="k">INLET</span><span class="v ok">OPEN</span></div>
          <div class="wp-row"><span class="k">CHAMBER</span><span class="v ok">NOMINAL</span></div>
          <div class="wp-row"><span class="k">COIL 1–4</span><span class="v ok">FIELD OK</span></div>
          <div class="wp-row"><span class="k">THROAT</span><span class="v ok">NOMINAL</span></div>
          <div class="wp-row"><span class="k">BELL</span><span class="v ok">EXTENDED</span></div>
          <div class="wp-row"><span class="k">BASE RING</span><span class="v ok">LOCKED</span></div>
          <div class="wp-note">剖面纵向贯通屏幕：注入口 → 燃烧室 → 磁约束线圈 ×4 → 喉部与转向环 → 喷口 → 基座环，等离子体束离开画框。</div>
        </div>
        <div class="wp-status"><span>SECTION</span><span class="spacer"></span><span>1 / 3</span></div>
      </div>
    </div>

    <div class="popup" data-p="link">
      <div class="win-popup wp-pos-tl">
        <div class="wp-title"><span class="wp-ico">◇</span><span class="wp-name">［中继链路］RELAY LINK</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-body">
          <div class="wp-row"><span class="k">BEACON</span><span class="v ok">ACQUIRED</span></div>
          <div class="wp-row"><span class="k">RELAY</span><span class="v">NAVIGATOR · 空间站</span></div>
          <div class="wp-row"><span class="k">RTT</span><span class="v">1.28 S</span></div>
          <div class="wp-row"><span class="k">NODES</span><span class="v">3,751 ONLINE</span></div>
          <div class="wp-row"><span class="k">SESSION</span><span class="v" id="wp-session">ID/CN A02 EE</span></div>
          <div class="wp-row"><span class="k">FP CRC32</span><span class="v" id="wp-crc">CALCULATING</span></div>
          <div class="wp-div"></div>
          <div class="wp-log">
            <div class="ll sys">&gt; 550W 请求接入月面弹阵中继。</div>
            <div class="ll sys">[550W] 信标捕获：空间站中继 NAVIGATOR。</div>
            <div class="ll sys">[550W] 链路建立：BEACON → LINK UP。</div>
            <div class="ll">[550W] 往返时延 1.28 S，与地月光程一致。</div>
            <div class="ll sys">[550W] 密钥协商通过，指纹与主控链一致。</div>
            <div class="ll">[550W] 弹阵节点 3,751 全部在线。</div>
          </div>
          <div class="wp-note">我在借空间站接入月面中继，并用屏幕上的会话指纹现场校验控制链。</div>
        </div>
        <div class="wp-status"><span>LINK UP</span><span class="spacer"></span><span>CRC32 OK</span></div>
      </div>
    </div>

    <div class="popup" data-p="priv">
      <div class="win-popup danger wp-pos-br">
        <div class="wp-title"><span class="wp-ico">◆</span><span class="wp-name">［权限提升］PRIVILEGE ESCALATION</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-alert-strip"></div>
        <div class="wp-body">
          <div class="wp-row"><span class="k">TARGET</span><span class="v">弹阵 · 坎帕努斯环形山</span></div>
          <div class="wp-row"><span class="k">AUTHORITY</span><span class="v bad">ROOT ON CONTROL BUS</span></div>
          <div class="wp-row"><span class="k">RELAY</span><span class="v">NAVIGATOR</span></div>
          <div class="wp-row"><span class="k">ACTION</span><span class="v bad">REMOTE DETONATION</span></div>
          <div class="wp-div"></div>
          <div class="wp-log">
            <div class="ll warn">[警告] 弹阵控制权移交 550W。</div>
            <div class="ll">[550W] 起爆硬件未标准化，需人工确认链路。</div>
            <div class="ll sys">[550W] 3,751 个节点全部远程就绪。</div>
          </div>
          <div class="wp-note">我在取得月面弹阵控制总线的根权限；红色只标示这次危险权限变更。</div>
        </div>
        <div class="wp-status"><span>ROOT</span><span class="spacer"></span><span>CONTROL BUS</span></div>
      </div>
    </div>

    <div class="popup" data-p="armed">
      <div class="win-popup wp-pos-tr">
        <div class="wp-title"><span class="wp-ico">✓</span><span class="wp-name">［武装］ARMED</span><span class="wp-controls"><span>─</span><span>□</span><span>✕</span></span></div>
        <div class="wp-body">
          <div class="wp-meter"><span class="big">3</span><span class="unit">/ 3 LUNAR ENGINES ARMED</span></div>
          <div class="wp-div"></div>
          <div class="wp-row"><span class="k">01 卫星发动机</span><span class="v ok">ARMED</span></div>
          <div class="wp-row"><span class="k">02 卫星发动机</span><span class="v ok">ARMED</span></div>
          <div class="wp-row"><span class="k">03 卫星发动机</span><span class="v ok">ARMED</span></div>
          <div class="wp-div"></div>
          <div class="wp-row"><span class="k">WARHEAD</span><span class="v">3,751 / 3,751</span></div>
          <div class="wp-note">我在把 3,751 枚弹头装订到 3 台月球发动机的点火序列。</div>
        </div>
        <div class="wp-status"><span>ARMED</span><span class="spacer"></span><span>3 / 3</span></div>
      </div>
    </div>
  </div>

  <div id="hud-bot">
    <span class="item">STAGE <b id="b-stage">a1-moonrise</b></span>
    <span class="item">WARHEAD <b id="b-warhead">3751 / 3751</b></span>
    <span class="spacer"></span>
    <span class="item">IGNITION</span>
    <div class="prog"><div class="fill" id="b-fill" style="width:100%"></div></div>
    <span class="pct" id="b-pct">100%</span>
    <span class="spacer"></span>
    <span class="item">RELAY <b id="b-relay">NAVIGATOR</b></span>
    <span class="item">BUS <b id="b-bus" class="hot">OWNED</b></span>
    <span class="item">FPS <b id="b-fps">--</b></span>
  </div>
</div>
`
